language: python
python:
- '3.5'
- '3.6'
- '3.7-dev'
install:
 - pip install pipenv
 - pipenv install --dev
script:
  - pipenv run -- mypy -p fst_lookup
  - pipenv run -- py.test
after_success:
  - codecov
